### ISSUE TITLE
Problem installing Barry on Lubuntu 20.04.1

### ISSUE THREAD

**Issue by Ivaylogi98** [lyubolp/Barry-Voice-Assistant#20]
All other steps finish successfully!
![image](https://user-images.githubusercontent.com/19604369/100543821-060f2280-325b-11eb-9705-2cd8eb354062.png)
![image](https://user-images.githubusercontent.com/19604369/100543824-08717c80-325b-11eb-9ec2-e78fab417527.png)
Running Lubuntu 20.04.1 on VirtualBox with settings:
![image](https://user-images.githubusercontent.com/19604369/100544015-bbda7100-325b-11eb-8bc9-02a5071b8c5d.png)

**Comment by luchev** [comment]
I see `pcre2-10.23.ziip: No space left on device, closing control connection`.
Are you sure you have enough free space? The installation requires a couple of Gigs.

**Comment by Ivaylogi98** [comment]
That solved the issue. Thanks!
